apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: triptailor-backend
spec:
  source:
    repoURL: https://github.com/usuario/triptailor
    path: k8s
    targetRevision: main
  destination:
    namespace: triptailor
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
